branches:
  only:
  - master
language: node_js
node_js:
- lts/*
git:
  depth: 30
install:
- yarn --frozen-lockfile
- yarn test
before_script:
- chmod 777 ./build.sh
- npm config set registry=http://registry.npmjs.org
script:
- "./build.sh"
after_script: 
cache: yarn
deploy:
- provider: npm
  skip_cleanup: true
  email: leezeehowe@gmail.com
  api_key: $NPM_TOKEN
  
